export const metadata = {
    title: "FIE",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div
        >
            {children}
        </div>
    );
}
